### ISSUE TITLE
Unable to apply filter on bool property

### ISSUE THREAD

**Issue by habib535** [Starcounter/ODataApi#34]
Checkout master-2.4 and start the app.

Navigate to the following URL
http://localhost:8080/odataApi/api/ODataApi__Test__Sample?$filter=Active eq true

```
System.NotImplementedException: The method or operation is not implemented.
   at ODataApi.OData.Handlers.SelectSetResponseHandler.Compare(BinaryOperatorNode expr, Func`3 func) in D:\Workspace\ODataApi\src\ODataApi\OData\Handlers\SelectSetResponseHandler.cs:line 253
   at ODataApi.OData.Handlers.SelectSetResponseHandler.BuildFilter(SqlBuilder sqlBuilder, BinaryOperatorNode expr) in D:\Workspace\ODataApi\src\ODataApi\OData\Handlers\SelectSetResponseHandler.cs:line 194
   at ODataApi.OData.Handlers.SelectSetResponseHandler.BuildFilter(SqlBuilder sqlBuilder, SingleValueNode expr) in D:\Workspace\ODataApi\src\ODataApi\OData\Handlers\SelectSetResponseHandler.cs:line 152
   at ODataApi.OData.Handlers.SelectSetResponseHandler.Handle(Request request) in D:\Workspace\ODataApi\src\ODataApi\OData\Handlers\SelectSetResponseHandler.cs:line 73
   at ODataApi.Api.MainHandlers.HandleDataRequest(Request request) in D:\Workspace\ODataApi\src\ODataApi\Api\MainHandlers.cs:line 39
   at ODataApi.Api.MainHandlers.<Register>b__0_2(String path, Request request) in D:\Workspace\ODataApi\src\ODataApi\Api\MainHandlers.cs:line 19
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-17312\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 202
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-17312\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 95
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-17312\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 359
HResult=-2147467263

More information about this error may be available in the server error log.
```

**Comment by un-tone** [comment]
@habib535 can this issue be closed after https://github.com/Starcounter/ODataApi/pull/35 PR merging?
